# Generated by Django 6.0.2 on 2026-03-04 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Used', 'Used')], default='Reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_login.computer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
