# Generated by Django 6.0.2 on 2026-03-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_login', '0002_computer_position_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pc_login.computer'),
        ),
    ]
