# Generated by Django 6.0.2 on 2026-03-05 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_login', '0003_alter_reservation_pc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_pc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
