# Generated by Django 6.0.2 on 2026-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('VIP', 'VIP'), ('Gaming', 'Gaming'), ('Regular', 'Regular'), ('Streaming', 'Streaming')], max_length=20)),
                ('pc_id', models.CharField(max_length=20, unique=True)),
                ('specs', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Reserved', 'Reserved'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], max_length=20)),
                ('maintenance_notes', models.TextField(blank=True)),
            ],
        ),
    ]
