# Generated by Django 6.0.2 on 2026-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_computer_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='maintenance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='specs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Reserved', 'Reserved'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
