# Generated by Django 6.0.2 on 2026-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_computer_maintenance_alter_computer_pc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
