# Generated by Django 6.0.2 on 2026-03-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_computer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Reserved', 'Reserved'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
