# Generated by Django 6.0.2 on 2026-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Reserved', 'Reserved'), ('Maintenance', 'Maintenance'), ('Offline', 'Offline')], default='Available', max_length=20),
        ),
    ]
